version: '3.8'

services:
  # -------------------------------------------------------------------
  # 1. Spring Boot 应用
  # -------------------------------------------------------------------
  app:
    container_name: ecode
    image: ghcr.io/xuanyue1024/e-code:test
    ports:
      - "8088:8088"
      - "465:465" #邮件服务
    restart: unless-stopped
    depends_on:
      # - mariadb
      chroma:
        condition: service_healthy
      redis:
        condition: service_started
    # 挂载宿主机 Docker Socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #代码运行支持
      - ./config/application-dev.yml:/app/application-dev.yml

  # -------------------------------------------------------------------
  # 2. MariaDB
  # -------------------------------------------------------------------
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-service
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: XW%1lk1vKu*W
      MYSQL_DATABASE: ecode
      # ports:
      # - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      # sql初始化
      - ./sql:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --performance-schema=0
      --table-open-cache=50
      --thread-cache-size=10
      --key-buffer-size=8M
      --innodb-buffer-pool-size=64M
      --innodb-log-buffer-size=8M
      --max-connections=50

  # -------------------------------------------------------------------
  # 3. Chroma 向量数据库
  # -------------------------------------------------------------------
  chroma:
    image: chromadb/chroma:0.4.15
    container_name: chroma-db
    restart: unless-stopped
      # ports:
    # - "8000:8000"
    volumes:
      - ./data/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_DISABLE_HNSWLIB_AUTOINSTALL=TRUE #禁用联网下载
      - ANONYMIZED_TELEMETRY=false   # 关闭遥测
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/heartbeat', timeout=5)"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 50s

  # -------------------------------------------------------------------
  # 4. Redis
  # -------------------------------------------------------------------
  redis:
    image: redis:alpine
    container_name: redis-service
    restart: unless-stopped
      # ports:
    # - "6379:6379"
    # 开启持久化 (AOF) 并设置密码为 '123456'
    # 如果不需要密码，去掉 --requirepass 123456 即可
    command: redis-server --appendonly yes --requirepass XW%1lk1vKu*W
    volumes:
      - ./data/redis:/data

networks:
  default:
    driver: bridge