version: '3.8'

services:
  # -------------------------------------------------------------------
  # 1. Spring Boot 应用
  # -------------------------------------------------------------------
  ecode:
    container_name: ecode
    image: ghcr.io/xuanyue1024/e-code:latest
    ports:
      - "127.0.0.1:8088:8088"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 114.114.114.114
    depends_on:
      # - mariadb
      redis:
        condition: service_started
    # 挂载宿主机 Docker Socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #代码运行支持
      - ./config/application-dev.yml:/app/application-dev.yml
      - ./logs:/app/logs

  # -------------------------------------------------------------------
  # 2. ecode-ui + nginx
  # -------------------------------------------------------------------
  ecode-ui:
    container_name: ecode-nginx
    image: ghcr.io/xuanyue1024/e-code-ui:latest
    restart: unless-stopped
    ports:
      - "8089:8088"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ecode

  # -------------------------------------------------------------------
  # 3. MariaDB
  # -------------------------------------------------------------------
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-service
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: XW%1lk1vKu*W
      MYSQL_DATABASE: ecode
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      # sql初始化
      - ./sql:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --performance-schema=0
      --table-open-cache=50
      --thread-cache-size=10
      --key-buffer-size=8M
      --innodb-buffer-pool-size=64M
      --innodb-log-buffer-size=8M
      --max-connections=50

  # -------------------------------------------------------------------
  # 4. Redis
  # -------------------------------------------------------------------
  redis:
    image: redis/redis-stack:7.2.0-v20
    container_name: redis-service
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      REDIS_ARGS: "--appendonly yes --requirepass XW%1lk1vKu*W"
    volumes:
      - ./data/redis:/data

networks:
  default:
    driver: bridge