version: '3.8'

services:
  # -------------------------------------------------------------------
  # 1. Spring Boot 应用
  # -------------------------------------------------------------------
  app:
    container_name: ecode
    image: ghcr.io/xuanyue1024/e-code:latest
    ports:
      - "8088:8088"
      - "465:465" #邮件服务
    restart: unless-stopped
    depends_on:
      # - mariadb
      redis:
        condition: service_started
    # 挂载宿主机 Docker Socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #代码运行支持
      - ./config/application-dev.yml:/app/application-dev.yml

  # -------------------------------------------------------------------
  # 2. MariaDB
  # -------------------------------------------------------------------
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-service
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: XW%1lk1vKu*W
      MYSQL_DATABASE: ecode
      # ports:
      # - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      # sql初始化
      - ./sql:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --performance-schema=0
      --table-open-cache=50
      --thread-cache-size=10
      --key-buffer-size=8M
      --innodb-buffer-pool-size=64M
      --innodb-log-buffer-size=8M
      --max-connections=50

  # -------------------------------------------------------------------
  # 3. Redis
  # -------------------------------------------------------------------
  redis:
    image: redis/redis-stack:7.2.0-v20
    container_name: redis-service
    restart: unless-stopped
#    ports:
#      - "6379:6379"
    environment:
      REDIS_ARGS: "--appendonly yes --requirepass XW%1lk1vKu*W"
    volumes:
      - ./data/redis:/data

networks:
  default:
    driver: bridge